# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

# CI for Sangria team project

name: Sangria CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Set up Java and Maven
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Test auth with Maven
      run: mvn clean test --file service-auth/pom.xml -DskipTests=false
    - name: Test operation with Maven
      run: mvn clean test --file service-operation/pom.xml -DskipTests=false
      
    
